// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

using SixLabors.ImageSharp.Formats.Av1.Bitstream;
using SixLabors.ImageSharp.Formats.Av1.Obu;

namespace SixLabors.ImageSharp.Codecs.Av1.Tests;

/// <summary>
/// Parses the inter frame header of a real error-resilient two-frame clip (16x16, generated by aomenc
/// with <c>--error-resilient=1</c>, so the inter frame uses no primary reference and no temporal motion
/// vectors - the implemented subset). Validates that <see cref="ObuFrameHeader.ParseInter"/> accepts the
/// frame and produces sensible inter fields.
/// </summary>
public class Av1InterFrameHeaderParseTests
{
    private static readonly byte[] SequencePayload = Convert.FromHexString("000000019fff036be601");
    private static readonly byte[] KeyFramePayload = Convert.FromHexString("100808014e0000049700000103b93151a17fa0");
    private static readonly byte[] InterFramePayload = Convert.FromHexString("3804080408000000000000000000000000000000000000000000001680000014580000001876");

    [Fact]
    public void ParseInter_RealErrorResilientClip_ProducesInterFields()
    {
        ObuSequenceHeader sequenceHeader = ObuSequenceHeader.Parse(SequencePayload);

        // The key frame establishes the reference-frame order hints.
        Av1BitStreamReader keyReader = new(KeyFramePayload);
        ObuFrameHeader keyHeader = ObuFrameHeader.ParseIntra(ref keyReader, sequenceHeader);
        int[] referenceOrderHints = new int[8];
        for (int slot = 0; slot < 8; slot++)
        {
            if ((keyHeader.RefreshFrameFlags & (1 << slot)) != 0)
            {
                referenceOrderHints[slot] = keyHeader.OrderHint;
            }
        }

        // The inter frame header must parse without hitting an unsupported-feature guard.
        Av1BitStreamReader interReader = new(InterFramePayload);
        ObuFrameHeader interHeader = ObuFrameHeader.ParseInter(ref interReader, sequenceHeader, referenceOrderHints);

        Assert.Equal(7, interHeader.PrimaryRefFrame); // PRIMARY_REF_NONE for error-resilient frames
        Assert.Equal(7, interHeader.ReferenceFrameIndices.Length);
        Assert.True(interHeader.RefreshFrameFlags is >= 0 and <= 0xFF);

        // The dimensions match the coded 16x16 frame.
        Assert.Equal(16, interHeader.FrameWidth);
        Assert.Equal(16, interHeader.FrameHeight);

        // The tile data starts after the header within the frame OBU.
        int tileGroupStart = (interHeader.EndBitPosition + 7) >> 3;
        Assert.InRange(tileGroupStart, 1, InterFramePayload.Length);
    }
}
