// <auto-generated>
// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.
//
// This file is a faithful, mechanical port of the AV1 reference 32- and 64-point inverse DCT
// butterfly networks (specification section 7.13.2.2). It is marked as generated so the
// parenthesisation and layout match the reference exactly, minimising transcription risk.
// </auto-generated>

namespace SixLabors.ImageSharp.Formats.Av1.Transform;

/// <content>
/// One-dimensional inverse DCT for the 32- and 64-point transforms (specification section 7.13.2.2).
/// </content>
internal static partial class Av1InverseTransform1d
{
    /// <summary>Applies the 32-point inverse DCT.</summary>
    /// <param name="c">The coefficient buffer.</param>
    /// <param name="offset">The offset of the first coefficient.</param>
    /// <param name="stride">The distance between consecutive coefficients.</param>
    /// <param name="min">The lower clamp bound.</param>
    /// <param name="max">The upper clamp bound.</param>
    public static void InverseDct32(Span<int> c, int offset, int stride, int min, int max)
        => InverseDct32(c, offset, stride, min, max, false);

    /// <summary>Applies the 64-point inverse DCT.</summary>
    /// <param name="c">The coefficient buffer.</param>
    /// <param name="offset">The offset of the first coefficient.</param>
    /// <param name="stride">The distance between consecutive coefficients.</param>
    /// <param name="min">The lower clamp bound.</param>
    /// <param name="max">The upper clamp bound.</param>
    public static void InverseDct64(Span<int> c, int offset, int stride, int min, int max)
    {
        int Cl(int v) => Clip(v, min, max);

    InverseDct32(c, offset, stride << 1, min, max, true);

    int in1  = c[offset + (1 * stride)], in3  = c[offset + (3 * stride)];
    int in5  = c[offset + (5 * stride)], in7  = c[offset + (7 * stride)];
    int in9  = c[offset + (9 * stride)], in11 = c[offset + (11 * stride)];
    int in13 = c[offset + (13 * stride)], in15 = c[offset + (15 * stride)];
    int in17 = c[offset + (17 * stride)], in19 = c[offset + (19 * stride)];
    int in21 = c[offset + (21 * stride)], in23 = c[offset + (23 * stride)];
    int in25 = c[offset + (25 * stride)], in27 = c[offset + (27 * stride)];
    int in29 = c[offset + (29 * stride)], in31 = c[offset + (31 * stride)];

    int t32a = (in1  *   101 + 2048) >> 12;
    int t33a = (in31 * -2824 + 2048) >> 12;
    int t34a = (in17 *  1660 + 2048) >> 12;
    int t35a = (in15 * -1474 + 2048) >> 12;
    int t36a = (in9  *   897 + 2048) >> 12;
    int t37a = (in23 * -2191 + 2048) >> 12;
    int t38a = (in25 *  2359 + 2048) >> 12;
    int t39a = (in7  *  -700 + 2048) >> 12;
    int t40a = (in5  *   501 + 2048) >> 12;
    int t41a = (in27 * -2520 + 2048) >> 12;
    int t42a = (in21 *  2019 + 2048) >> 12;
    int t43a = (in11 * -1092 + 2048) >> 12;
    int t44a = (in13 *  1285 + 2048) >> 12;
    int t45a = (in19 * -1842 + 2048) >> 12;
    int t46a = (in29 *  2675 + 2048) >> 12;
    int t47a = (in3  *  -301 + 2048) >> 12;
    int t48a = (in3  *  4085 + 2048) >> 12;
    int t49a = (in29 *  3102 + 2048) >> 12;
    int t50a = (in19 *  3659 + 2048) >> 12;
    int t51a = (in13 *  3889 + 2048) >> 12;
    int t52a = (in11 *  3948 + 2048) >> 12;
    int t53a = (in21 *  3564 + 2048) >> 12;
    int t54a = (in27 *  3229 + 2048) >> 12;
    int t55a = (in5  *  4065 + 2048) >> 12;
    int t56a = (in7  *  4036 + 2048) >> 12;
    int t57a = (in25 *  3349 + 2048) >> 12;
    int t58a = (in23 *  3461 + 2048) >> 12;
    int t59a = (in9  *  3996 + 2048) >> 12;
    int t60a = (in15 *  3822 + 2048) >> 12;
    int t61a = (in17 *  3745 + 2048) >> 12;
    int t62a = (in31 *  2967 + 2048) >> 12;
    int t63a = (in1  *  4095 + 2048) >> 12;

    int t32 = Cl(t32a + t33a);
    int t33 = Cl(t32a - t33a);
    int t34 = Cl(t35a - t34a);
    int t35 = Cl(t35a + t34a);
    int t36 = Cl(t36a + t37a);
    int t37 = Cl(t36a - t37a);
    int t38 = Cl(t39a - t38a);
    int t39 = Cl(t39a + t38a);
    int t40 = Cl(t40a + t41a);
    int t41 = Cl(t40a - t41a);
    int t42 = Cl(t43a - t42a);
    int t43 = Cl(t43a + t42a);
    int t44 = Cl(t44a + t45a);
    int t45 = Cl(t44a - t45a);
    int t46 = Cl(t47a - t46a);
    int t47 = Cl(t47a + t46a);
    int t48 = Cl(t48a + t49a);
    int t49 = Cl(t48a - t49a);
    int t50 = Cl(t51a - t50a);
    int t51 = Cl(t51a + t50a);
    int t52 = Cl(t52a + t53a);
    int t53 = Cl(t52a - t53a);
    int t54 = Cl(t55a - t54a);
    int t55 = Cl(t55a + t54a);
    int t56 = Cl(t56a + t57a);
    int t57 = Cl(t56a - t57a);
    int t58 = Cl(t59a - t58a);
    int t59 = Cl(t59a + t58a);
    int t60 = Cl(t60a + t61a);
    int t61 = Cl(t60a - t61a);
    int t62 = Cl(t63a - t62a);
    int t63 = Cl(t63a + t62a);

    t33a = ((t33 * (4096 - 4076) + t62 *   401         + 2048) >> 12) - t33;
    t34a = ((t34 *  -401         + t61 * (4096 - 4076) + 2048) >> 12) - t61;
    t37a =  (t37 * -1299         + t58 *  1583         + 1024) >> 11;
    t38a =  (t38 * -1583         + t57 * -1299         + 1024) >> 11;
    t41a = ((t41 * (4096 - 3612) + t54 *  1931         + 2048) >> 12) - t41;
    t42a = ((t42 * -1931         + t53 * (4096 - 3612) + 2048) >> 12) - t53;
    t45a = ((t45 * -1189         + t50 * (3920 - 4096) + 2048) >> 12) + t50;
    t46a = ((t46 * (4096 - 3920) + t49 * -1189         + 2048) >> 12) - t46;
    t49a = ((t46 * -1189         + t49 * (3920 - 4096) + 2048) >> 12) + t49;
    t50a = ((t45 * (3920 - 4096) + t50 *  1189         + 2048) >> 12) + t45;
    t53a = ((t42 * (4096 - 3612) + t53 *  1931         + 2048) >> 12) - t42;
    t54a = ((t41 *  1931         + t54 * (3612 - 4096) + 2048) >> 12) + t54;
    t57a =  (t38 * -1299         + t57 *  1583         + 1024) >> 11;
    t58a =  (t37 *  1583         + t58 *  1299         + 1024) >> 11;
    t61a = ((t34 * (4096 - 4076) + t61 *   401         + 2048) >> 12) - t34;
    t62a = ((t33 *   401         + t62 * (4076 - 4096) + 2048) >> 12) + t62;

    t32a = Cl(t32  + t35);
    t33  = Cl(t33a + t34a);
    t34  = Cl(t33a - t34a);
    t35a = Cl(t32  - t35);
    t36a = Cl(t39  - t36);
    t37  = Cl(t38a - t37a);
    t38  = Cl(t38a + t37a);
    t39a = Cl(t39  + t36);
    t40a = Cl(t40  + t43);
    t41  = Cl(t41a + t42a);
    t42  = Cl(t41a - t42a);
    t43a = Cl(t40  - t43);
    t44a = Cl(t47  - t44);
    t45  = Cl(t46a - t45a);
    t46  = Cl(t46a + t45a);
    t47a = Cl(t47  + t44);
    t48a = Cl(t48  + t51);
    t49  = Cl(t49a + t50a);
    t50  = Cl(t49a - t50a);
    t51a = Cl(t48  - t51);
    t52a = Cl(t55  - t52);
    t53  = Cl(t54a - t53a);
    t54  = Cl(t54a + t53a);
    t55a = Cl(t55  + t52);
    t56a = Cl(t56  + t59);
    t57  = Cl(t57a + t58a);
    t58  = Cl(t57a - t58a);
    t59a = Cl(t56  - t59);
    t60a = Cl(t63  - t60);
    t61  = Cl(t62a - t61a);
    t62  = Cl(t62a + t61a);
    t63a = Cl(t63  + t60);

    t34a = ((t34  * (4096 - 4017) + t61  *   799         + 2048) >> 12) - t34;
    t35  = ((t35a * (4096 - 4017) + t60a *   799         + 2048) >> 12) - t35a;
    t36  = ((t36a *  -799         + t59a * (4096 - 4017) + 2048) >> 12) - t59a;
    t37a = ((t37  *  -799         + t58  * (4096 - 4017) + 2048) >> 12) - t58;
    t42a =  (t42  * -1138         + t53  *  1703         + 1024) >> 11;
    t43  =  (t43a * -1138         + t52a *  1703         + 1024) >> 11;
    t44  =  (t44a * -1703         + t51a * -1138         + 1024) >> 11;
    t45a =  (t45  * -1703         + t50  * -1138         + 1024) >> 11;
    t50a =  (t45  * -1138         + t50  *  1703         + 1024) >> 11;
    t51  =  (t44a * -1138         + t51a *  1703         + 1024) >> 11;
    t52  =  (t43a *  1703         + t52a *  1138         + 1024) >> 11;
    t53a =  (t42  *  1703         + t53  *  1138         + 1024) >> 11;
    t58a = ((t37  * (4096 - 4017) + t58  *   799         + 2048) >> 12) - t37;
    t59  = ((t36a * (4096 - 4017) + t59a *   799         + 2048) >> 12) - t36a;
    t60  = ((t35a *   799         + t60a * (4017 - 4096) + 2048) >> 12) + t60a;
    t61a = ((t34  *   799         + t61  * (4017 - 4096) + 2048) >> 12) + t61;

    t32  = Cl(t32a + t39a);
    t33a = Cl(t33  + t38);
    t34  = Cl(t34a + t37a);
    t35a = Cl(t35  + t36);
    t36a = Cl(t35  - t36);
    t37  = Cl(t34a - t37a);
    t38a = Cl(t33  - t38);
    t39  = Cl(t32a - t39a);
    t40  = Cl(t47a - t40a);
    t41a = Cl(t46  - t41);
    t42  = Cl(t45a - t42a);
    t43a = Cl(t44  - t43);
    t44a = Cl(t44  + t43);
    t45  = Cl(t45a + t42a);
    t46a = Cl(t46  + t41);
    t47  = Cl(t47a + t40a);
    t48  = Cl(t48a + t55a);
    t49a = Cl(t49  + t54);
    t50  = Cl(t50a + t53a);
    t51a = Cl(t51  + t52);
    t52a = Cl(t51  - t52);
    t53  = Cl(t50a - t53a);
    t54a = Cl(t49  - t54);
    t55  = Cl(t48a - t55a);
    t56  = Cl(t63a - t56a);
    t57a = Cl(t62  - t57);
    t58  = Cl(t61a - t58a);
    t59a = Cl(t60  - t59);
    t60a = Cl(t60  + t59);
    t61  = Cl(t61a + t58a);
    t62a = Cl(t62  + t57);
    t63  = Cl(t63a + t56a);

    t36  = ((t36a * (4096 - 3784) + t59a *  1567         + 2048) >> 12) - t36a;
    t37a = ((t37  * (4096 - 3784) + t58  *  1567         + 2048) >> 12) - t37;
    t38  = ((t38a * (4096 - 3784) + t57a *  1567         + 2048) >> 12) - t38a;
    t39a = ((t39  * (4096 - 3784) + t56  *  1567         + 2048) >> 12) - t39;
    t40a = ((t40  * -1567         + t55  * (4096 - 3784) + 2048) >> 12) - t55;
    t41  = ((t41a * -1567         + t54a * (4096 - 3784) + 2048) >> 12) - t54a;
    t42a = ((t42  * -1567         + t53  * (4096 - 3784) + 2048) >> 12) - t53;
    t43  = ((t43a * -1567         + t52a * (4096 - 3784) + 2048) >> 12) - t52a;
    t52  = ((t43a * (4096 - 3784) + t52a *  1567         + 2048) >> 12) - t43a;
    t53a = ((t42  * (4096 - 3784) + t53  *  1567         + 2048) >> 12) - t42;
    t54  = ((t41a * (4096 - 3784) + t54a *  1567         + 2048) >> 12) - t41a;
    t55a = ((t40  * (4096 - 3784) + t55  *  1567         + 2048) >> 12) - t40;
    t56a = ((t39  *  1567         + t56  * (3784 - 4096) + 2048) >> 12) + t56;
    t57  = ((t38a *  1567         + t57a * (3784 - 4096) + 2048) >> 12) + t57a;
    t58a = ((t37  *  1567         + t58  * (3784 - 4096) + 2048) >> 12) + t58;
    t59  = ((t36a *  1567         + t59a * (3784 - 4096) + 2048) >> 12) + t59a;

    t32a = Cl(t32  + t47);
    t33  = Cl(t33a + t46a);
    t34a = Cl(t34  + t45);
    t35  = Cl(t35a + t44a);
    t36a = Cl(t36  + t43);
    t37  = Cl(t37a + t42a);
    t38a = Cl(t38  + t41);
    t39  = Cl(t39a + t40a);
    t40  = Cl(t39a - t40a);
    t41a = Cl(t38  - t41);
    t42  = Cl(t37a - t42a);
    t43a = Cl(t36  - t43);
    t44  = Cl(t35a - t44a);
    t45a = Cl(t34  - t45);
    t46  = Cl(t33a - t46a);
    t47a = Cl(t32  - t47);
    t48a = Cl(t63  - t48);
    t49  = Cl(t62a - t49a);
    t50a = Cl(t61  - t50);
    t51  = Cl(t60a - t51a);
    t52a = Cl(t59  - t52);
    t53  = Cl(t58a - t53a);
    t54a = Cl(t57  - t54);
    t55  = Cl(t56a - t55a);
    t56  = Cl(t56a + t55a);
    t57a = Cl(t57  + t54);
    t58  = Cl(t58a + t53a);
    t59a = Cl(t59  + t52);
    t60  = Cl(t60a + t51a);
    t61a = Cl(t61  + t50);
    t62  = Cl(t62a + t49a);
    t63a = Cl(t63  + t48);

    t40a = ((t55  - t40 ) * 181 + 128) >> 8;
    t41  = ((t54a - t41a) * 181 + 128) >> 8;
    t42a = ((t53  - t42 ) * 181 + 128) >> 8;
    t43  = ((t52a - t43a) * 181 + 128) >> 8;
    t44a = ((t51  - t44 ) * 181 + 128) >> 8;
    t45  = ((t50a - t45a) * 181 + 128) >> 8;
    t46a = ((t49  - t46 ) * 181 + 128) >> 8;
    t47  = ((t48a - t47a) * 181 + 128) >> 8;
    t48  = ((t47a + t48a) * 181 + 128) >> 8;
    t49a = ((t46  + t49 ) * 181 + 128) >> 8;
    t50  = ((t45a + t50a) * 181 + 128) >> 8;
    t51a = ((t44  + t51 ) * 181 + 128) >> 8;
    t52  = ((t43a + t52a) * 181 + 128) >> 8;
    t53a = ((t42  + t53 ) * 181 + 128) >> 8;
    t54  = ((t41a + t54a) * 181 + 128) >> 8;
    t55a = ((t40  + t55 ) * 181 + 128) >> 8;

    int t0  = c[offset + (0 * stride)];
    int t1  = c[offset + (2 * stride)];
    int t2  = c[offset + (4 * stride)];
    int t3  = c[offset + (6 * stride)];
    int t4  = c[offset + (8 * stride)];
    int t5  = c[offset + (10 * stride)];
    int t6  = c[offset + (12 * stride)];
    int t7  = c[offset + (14 * stride)];
    int t8  = c[offset + (16 * stride)];
    int t9  = c[offset + (18 * stride)];
    int t10 = c[offset + (20 * stride)];
    int t11 = c[offset + (22 * stride)];
    int t12 = c[offset + (24 * stride)];
    int t13 = c[offset + (26 * stride)];
    int t14 = c[offset + (28 * stride)];
    int t15 = c[offset + (30 * stride)];
    int t16 = c[offset + (32 * stride)];
    int t17 = c[offset + (34 * stride)];
    int t18 = c[offset + (36 * stride)];
    int t19 = c[offset + (38 * stride)];
    int t20 = c[offset + (40 * stride)];
    int t21 = c[offset + (42 * stride)];
    int t22 = c[offset + (44 * stride)];
    int t23 = c[offset + (46 * stride)];
    int t24 = c[offset + (48 * stride)];
    int t25 = c[offset + (50 * stride)];
    int t26 = c[offset + (52 * stride)];
    int t27 = c[offset + (54 * stride)];
    int t28 = c[offset + (56 * stride)];
    int t29 = c[offset + (58 * stride)];
    int t30 = c[offset + (60 * stride)];
    int t31 = c[offset + (62 * stride)];

    c[offset + (0 * stride)] = Cl(t0  + t63a);
    c[offset + (1 * stride)] = Cl(t1  + t62);
    c[offset + (2 * stride)] = Cl(t2  + t61a);
    c[offset + (3 * stride)] = Cl(t3  + t60);
    c[offset + (4 * stride)] = Cl(t4  + t59a);
    c[offset + (5 * stride)] = Cl(t5  + t58);
    c[offset + (6 * stride)] = Cl(t6  + t57a);
    c[offset + (7 * stride)] = Cl(t7  + t56);
    c[offset + (8 * stride)] = Cl(t8  + t55a);
    c[offset + (9 * stride)] = Cl(t9  + t54);
    c[offset + (10 * stride)] = Cl(t10 + t53a);
    c[offset + (11 * stride)] = Cl(t11 + t52);
    c[offset + (12 * stride)] = Cl(t12 + t51a);
    c[offset + (13 * stride)] = Cl(t13 + t50);
    c[offset + (14 * stride)] = Cl(t14 + t49a);
    c[offset + (15 * stride)] = Cl(t15 + t48);
    c[offset + (16 * stride)] = Cl(t16 + t47);
    c[offset + (17 * stride)] = Cl(t17 + t46a);
    c[offset + (18 * stride)] = Cl(t18 + t45);
    c[offset + (19 * stride)] = Cl(t19 + t44a);
    c[offset + (20 * stride)] = Cl(t20 + t43);
    c[offset + (21 * stride)] = Cl(t21 + t42a);
    c[offset + (22 * stride)] = Cl(t22 + t41);
    c[offset + (23 * stride)] = Cl(t23 + t40a);
    c[offset + (24 * stride)] = Cl(t24 + t39);
    c[offset + (25 * stride)] = Cl(t25 + t38a);
    c[offset + (26 * stride)] = Cl(t26 + t37);
    c[offset + (27 * stride)] = Cl(t27 + t36a);
    c[offset + (28 * stride)] = Cl(t28 + t35);
    c[offset + (29 * stride)] = Cl(t29 + t34a);
    c[offset + (30 * stride)] = Cl(t30 + t33);
    c[offset + (31 * stride)] = Cl(t31 + t32a);
    c[offset + (32 * stride)] = Cl(t31 - t32a);
    c[offset + (33 * stride)] = Cl(t30 - t33);
    c[offset + (34 * stride)] = Cl(t29 - t34a);
    c[offset + (35 * stride)] = Cl(t28 - t35);
    c[offset + (36 * stride)] = Cl(t27 - t36a);
    c[offset + (37 * stride)] = Cl(t26 - t37);
    c[offset + (38 * stride)] = Cl(t25 - t38a);
    c[offset + (39 * stride)] = Cl(t24 - t39);
    c[offset + (40 * stride)] = Cl(t23 - t40a);
    c[offset + (41 * stride)] = Cl(t22 - t41);
    c[offset + (42 * stride)] = Cl(t21 - t42a);
    c[offset + (43 * stride)] = Cl(t20 - t43);
    c[offset + (44 * stride)] = Cl(t19 - t44a);
    c[offset + (45 * stride)] = Cl(t18 - t45);
    c[offset + (46 * stride)] = Cl(t17 - t46a);
    c[offset + (47 * stride)] = Cl(t16 - t47);
    c[offset + (48 * stride)] = Cl(t15 - t48);
    c[offset + (49 * stride)] = Cl(t14 - t49a);
    c[offset + (50 * stride)] = Cl(t13 - t50);
    c[offset + (51 * stride)] = Cl(t12 - t51a);
    c[offset + (52 * stride)] = Cl(t11 - t52);
    c[offset + (53 * stride)] = Cl(t10 - t53a);
    c[offset + (54 * stride)] = Cl(t9  - t54);
    c[offset + (55 * stride)] = Cl(t8  - t55a);
    c[offset + (56 * stride)] = Cl(t7  - t56);
    c[offset + (57 * stride)] = Cl(t6  - t57a);
    c[offset + (58 * stride)] = Cl(t5  - t58);
    c[offset + (59 * stride)] = Cl(t4  - t59a);
    c[offset + (60 * stride)] = Cl(t3  - t60);
    c[offset + (61 * stride)] = Cl(t2  - t61a);
    c[offset + (62 * stride)] = Cl(t1  - t62);
    c[offset + (63 * stride)] = Cl(t0  - t63a);

    }

    private static void InverseDct32(Span<int> c, int offset, int stride, int min, int max, bool tx64)
    {
        int Cl(int v) => Clip(v, min, max);

    InverseDct16(c, offset, stride << 1, min, max, tx64);

    int in1  = c[offset + (1 * stride)], in3  = c[offset + (3 * stride)];
    int in5  = c[offset + (5 * stride)], in7  = c[offset + (7 * stride)];
    int in9  = c[offset + (9 * stride)], in11 = c[offset + (11 * stride)];
    int in13 = c[offset + (13 * stride)], in15 = c[offset + (15 * stride)];

    int t16a, t17a, t18a, t19a, t20a, t21a, t22a, t23a;
    int t24a, t25a, t26a, t27a, t28a, t29a, t30a, t31a;
    if (tx64) {
        t16a = (in1  *   201 + 2048) >> 12;
        t17a = (in15 * -2751 + 2048) >> 12;
        t18a = (in9  *  1751 + 2048) >> 12;
        t19a = (in7  * -1380 + 2048) >> 12;
        t20a = (in5  *   995 + 2048) >> 12;
        t21a = (in11 * -2106 + 2048) >> 12;
        t22a = (in13 *  2440 + 2048) >> 12;
        t23a = (in3  *  -601 + 2048) >> 12;
        t24a = (in3  *  4052 + 2048) >> 12;
        t25a = (in13 *  3290 + 2048) >> 12;
        t26a = (in11 *  3513 + 2048) >> 12;
        t27a = (in5  *  3973 + 2048) >> 12;
        t28a = (in7  *  3857 + 2048) >> 12;
        t29a = (in9  *  3703 + 2048) >> 12;
        t30a = (in15 *  3035 + 2048) >> 12;
        t31a = (in1  *  4091 + 2048) >> 12;
    } else {
        int in17 = c[offset + (17 * stride)], in19 = c[offset + (19 * stride)];
        int in21 = c[offset + (21 * stride)], in23 = c[offset + (23 * stride)];
        int in25 = c[offset + (25 * stride)], in27 = c[offset + (27 * stride)];
        int in29 = c[offset + (29 * stride)], in31 = c[offset + (31 * stride)];

        t16a = ((in1  *   201         - in31 * (4091 - 4096) + 2048) >> 12) - in31;
        t17a = ((in17 * (3035 - 4096) - in15 *  2751         + 2048) >> 12) + in17;
        t18a = ((in9  *  1751         - in23 * (3703 - 4096) + 2048) >> 12) - in23;
        t19a = ((in25 * (3857 - 4096) - in7  *  1380         + 2048) >> 12) + in25;
        t20a = ((in5  *   995         - in27 * (3973 - 4096) + 2048) >> 12) - in27;
        t21a = ((in21 * (3513 - 4096) - in11 *  2106         + 2048) >> 12) + in21;
        t22a =  (in13 *  1220         - in19 *  1645         + 1024) >> 11;
        t23a = ((in29 * (4052 - 4096) - in3  *   601         + 2048) >> 12) + in29;
        t24a = ((in29 *   601         + in3  * (4052 - 4096) + 2048) >> 12) + in3;
        t25a =  (in13 *  1645         + in19 *  1220         + 1024) >> 11;
        t26a = ((in21 *  2106         + in11 * (3513 - 4096) + 2048) >> 12) + in11;
        t27a = ((in5  * (3973 - 4096) + in27 *   995         + 2048) >> 12) + in5;
        t28a = ((in25 *  1380         + in7  * (3857 - 4096) + 2048) >> 12) + in7;
        t29a = ((in9  * (3703 - 4096) + in23 *  1751         + 2048) >> 12) + in9;
        t30a = ((in17 *  2751         + in15 * (3035 - 4096) + 2048) >> 12) + in15;
        t31a = ((in1  * (4091 - 4096) + in31 *   201         + 2048) >> 12) + in1;
    }

    int t16 = Cl(t16a + t17a);
    int t17 = Cl(t16a - t17a);
    int t18 = Cl(t19a - t18a);
    int t19 = Cl(t19a + t18a);
    int t20 = Cl(t20a + t21a);
    int t21 = Cl(t20a - t21a);
    int t22 = Cl(t23a - t22a);
    int t23 = Cl(t23a + t22a);
    int t24 = Cl(t24a + t25a);
    int t25 = Cl(t24a - t25a);
    int t26 = Cl(t27a - t26a);
    int t27 = Cl(t27a + t26a);
    int t28 = Cl(t28a + t29a);
    int t29 = Cl(t28a - t29a);
    int t30 = Cl(t31a - t30a);
    int t31 = Cl(t31a + t30a);

    t17a = ((  t30 *   799         - t17 * (4017 - 4096)  + 2048) >> 12) - t17;
    t30a = ((  t30 * (4017 - 4096) + t17 *   799          + 2048) >> 12) + t30;
    t18a = ((-(t29 * (4017 - 4096) + t18 *   799)         + 2048) >> 12) - t29;
    t29a = ((  t29 *   799         - t18 * (4017 - 4096)  + 2048) >> 12) - t18;
    t21a =  (  t26 *  1703         - t21 *  1138          + 1024) >> 11;
    t26a =  (  t26 *  1138         + t21 *  1703          + 1024) >> 11;
    t22a =  (-(t25 *  1138         + t22 *  1703        ) + 1024) >> 11;
    t25a =  (  t25 *  1703         - t22 *  1138          + 1024) >> 11;

    t16a = Cl(t16  + t19);
    t17  = Cl(t17a + t18a);
    t18  = Cl(t17a - t18a);
    t19a = Cl(t16  - t19);
    t20a = Cl(t23  - t20);
    t21  = Cl(t22a - t21a);
    t22  = Cl(t22a + t21a);
    t23a = Cl(t23  + t20);
    t24a = Cl(t24  + t27);
    t25  = Cl(t25a + t26a);
    t26  = Cl(t25a - t26a);
    t27a = Cl(t24  - t27);
    t28a = Cl(t31  - t28);
    t29  = Cl(t30a - t29a);
    t30  = Cl(t30a + t29a);
    t31a = Cl(t31  + t28);

    t18a = ((  t29  *  1567         - t18  * (3784 - 4096)  + 2048) >> 12) - t18;
    t29a = ((  t29  * (3784 - 4096) + t18  *  1567          + 2048) >> 12) + t29;
    t19  = ((  t28a *  1567         - t19a * (3784 - 4096)  + 2048) >> 12) - t19a;
    t28  = ((  t28a * (3784 - 4096) + t19a *  1567          + 2048) >> 12) + t28a;
    t20  = ((-(t27a * (3784 - 4096) + t20a *  1567)         + 2048) >> 12) - t27a;
    t27  = ((  t27a *  1567         - t20a * (3784 - 4096)  + 2048) >> 12) - t20a;
    t21a = ((-(t26  * (3784 - 4096) + t21  *  1567)         + 2048) >> 12) - t26;
    t26a = ((  t26  *  1567         - t21  * (3784 - 4096)  + 2048) >> 12) - t21;

    t16  = Cl(t16a + t23a);
    t17a = Cl(t17  + t22);
    t18  = Cl(t18a + t21a);
    t19a = Cl(t19  + t20);
    t20a = Cl(t19  - t20);
    t21  = Cl(t18a - t21a);
    t22a = Cl(t17  - t22);
    t23  = Cl(t16a - t23a);
    t24  = Cl(t31a - t24a);
    t25a = Cl(t30  - t25);
    t26  = Cl(t29a - t26a);
    t27a = Cl(t28  - t27);
    t28a = Cl(t28  + t27);
    t29  = Cl(t29a + t26a);
    t30a = Cl(t30  + t25);
    t31  = Cl(t31a + t24a);

    t20  = ((t27a - t20a) * 181 + 128) >> 8;
    t27  = ((t27a + t20a) * 181 + 128) >> 8;
    t21a = ((t26  - t21 ) * 181 + 128) >> 8;
    t26a = ((t26  + t21 ) * 181 + 128) >> 8;
    t22  = ((t25a - t22a) * 181 + 128) >> 8;
    t25  = ((t25a + t22a) * 181 + 128) >> 8;
    t23a = ((t24  - t23 ) * 181 + 128) >> 8;
    t24a = ((t24  + t23 ) * 181 + 128) >> 8;

    int t0  = c[offset + (0 * stride)];
    int t1  = c[offset + (2 * stride)];
    int t2  = c[offset + (4 * stride)];
    int t3  = c[offset + (6 * stride)];
    int t4  = c[offset + (8 * stride)];
    int t5  = c[offset + (10 * stride)];
    int t6  = c[offset + (12 * stride)];
    int t7  = c[offset + (14 * stride)];
    int t8  = c[offset + (16 * stride)];
    int t9  = c[offset + (18 * stride)];
    int t10 = c[offset + (20 * stride)];
    int t11 = c[offset + (22 * stride)];
    int t12 = c[offset + (24 * stride)];
    int t13 = c[offset + (26 * stride)];
    int t14 = c[offset + (28 * stride)];
    int t15 = c[offset + (30 * stride)];

    c[offset + (0 * stride)] = Cl(t0  + t31);
    c[offset + (1 * stride)] = Cl(t1  + t30a);
    c[offset + (2 * stride)] = Cl(t2  + t29);
    c[offset + (3 * stride)] = Cl(t3  + t28a);
    c[offset + (4 * stride)] = Cl(t4  + t27);
    c[offset + (5 * stride)] = Cl(t5  + t26a);
    c[offset + (6 * stride)] = Cl(t6  + t25);
    c[offset + (7 * stride)] = Cl(t7  + t24a);
    c[offset + (8 * stride)] = Cl(t8  + t23a);
    c[offset + (9 * stride)] = Cl(t9  + t22);
    c[offset + (10 * stride)] = Cl(t10 + t21a);
    c[offset + (11 * stride)] = Cl(t11 + t20);
    c[offset + (12 * stride)] = Cl(t12 + t19a);
    c[offset + (13 * stride)] = Cl(t13 + t18);
    c[offset + (14 * stride)] = Cl(t14 + t17a);
    c[offset + (15 * stride)] = Cl(t15 + t16);
    c[offset + (16 * stride)] = Cl(t15 - t16);
    c[offset + (17 * stride)] = Cl(t14 - t17a);
    c[offset + (18 * stride)] = Cl(t13 - t18);
    c[offset + (19 * stride)] = Cl(t12 - t19a);
    c[offset + (20 * stride)] = Cl(t11 - t20);
    c[offset + (21 * stride)] = Cl(t10 - t21a);
    c[offset + (22 * stride)] = Cl(t9  - t22);
    c[offset + (23 * stride)] = Cl(t8  - t23a);
    c[offset + (24 * stride)] = Cl(t7  - t24a);
    c[offset + (25 * stride)] = Cl(t6  - t25);
    c[offset + (26 * stride)] = Cl(t5  - t26a);
    c[offset + (27 * stride)] = Cl(t4  - t27);
    c[offset + (28 * stride)] = Cl(t3  - t28a);
    c[offset + (29 * stride)] = Cl(t2  - t29);
    c[offset + (30 * stride)] = Cl(t1  - t30a);
    c[offset + (31 * stride)] = Cl(t0  - t31);

    }
}
